# Generated by Django 2.2 on 2020-08-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginfo',
            name='address',
            field=models.CharField(max_length=200, verbose_name='机构地址'),
        ),
    ]
